<?php

use srag\DIC\DhbwTraining\DICTrait;

/**
 * Class xdhtExportGUI
 *
 * @author       : Benjamin Seglias   <bs@studer-raimann.ch>
 *
 * @ilCtrl_Calls xdhtExportGUI:
 */
class xdhtExportGUI extends ilExportGUI
{

    use DICTrait;
    const PLUGIN_CLASS_NAME = ilDhbwTrainingPlugin::class;
    const CMD_INDEX = 'buildExportTableGUI';

    /**
     * #SUR# component repository getPluginSlotById
     * @return void
     * @throws ilException
     */
    public function __construct($a_parent_gui, $a_main_obj = null)
    {
        global $DIC, $ilPluginAdmin;
        $lng = $DIC->language();
        /** @var ilComponentRepository $component_repository */
        $component_repository = $DIC["component.repository"];

        parent::__construct($a_parent_gui, $a_main_obj);

        $this->addFormat('xml', $lng->txt('ass_create_export_file'));

        /*
        $pl_names = $DIC["component.factory"]->getActivePluginsInSlot("xdht");

        foreach ($pl_names as $plugin) {
            /**
             * @var $plugin ilTestExportPlugin

            $this->addFormat(
                $plugin->getFormat(),
                $plugin->getFormatLabel(),
                $plugin,
                'export'
            );
        }*/
    }

    /**
     * #SUR# Return type declaration
     * @return void
     */
    public function executeCommand(): void
    {
        parent::executeCommand(); // TODO: Change the autogenerated stub
        self::dic()->ui()->mainTemplate()->printToStdout();
    }

    /**
     * #SUR# Return type declaration
     * @return void
     * @throws ilCtrlException
     */
    public function download(): void
    {
        /**
         * @var $lng    ilLanguage
         * @var $ilCtrl ilCtrl
         */
        global $lng, $ilCtrl;
        $file=array($_GET['file']);

        if (isset($_GET['file']) && $_GET['file']) {

            $file = array($_GET['file']);
        }

        if (!isset($file)) {
            //ilUtil::sendInfo($lng->txt('no_checkbox'), true);
            $this->tpl->setOnScreenMessage('info',$lng->txt('no_checkbox'),true);
            $ilCtrl->redirect($this, 'listExportFiles');
        }

        if (count($file) > 1) {
            //ilUtil::sendInfo($lng->txt('select_max_one_item'), true);
            $this->tpl->setOnScreenMessage('info',$lng->txt('select_max_one_item'),true);
            $ilCtrl->redirect($this, 'listExportFiles');
        }

        $filename = basename($file[0]);
        $exportFile = $this->getExportDirectory() . '/' . $filename;

        if (file_exists($exportFile)) {
            ilUtil::deliverData($exportFile, $filename);
        }

        $ilCtrl->redirect($this, 'listExportFiles');
    }


    /**
     * Get the location of the export directory for the xdhtSetting
     *
     * @access    public
     */
    function getExportDirectory()
    {
        $export_dir = ilFileUtils::getDataDir() . "/xdht_data" . "/xdht_" . $this->obj->getId() . "/export";

        return $export_dir;
    }

    /**
     * #SUR# Return type declaration
     * @return void
     * @throws ilCtrlException
     */
    public function delete(): void
    {
        /**
         * @var $lng    ilLanguage
         * @var $ilCtrl ilCtrl
         */
        global $lng, $ilCtrl;

        $export_dir = $this->getExportDirectory();
        foreach ($_POST['file'] as $file) {
            $file = basename($file);
            $dir = substr($file, 0, strlen($file) - 4);

            if (!strlen($file) || !strlen($dir)) {
                continue;
            }

            $exp_file = $export_dir . '/' . $file;
            $exp_dir = $export_dir . '/' . $dir;
            if (@is_file($exp_file)) {
                unlink($exp_file);
            }
            if (@is_dir($exp_dir)) {
                ilUtil::delDir($exp_dir);
            }
        }
        //ilUtil::sendSuccess($lng->txt('msg_deleted_export_files'), true);
        $this->tpl->setOnScreenMessage('success',$lng->txt('msg_deleted_export_files'),true);
        $ilCtrl->redirect($this, 'listExportFiles');
    }


    /**
     * #SUR# Return type declaration
     * @return xdhtExportTableGUI
     */
    protected function buildExportTableGUI(): xdhtExportTableGUI
    {
        $table = new xdhtExportTableGUI($this, 'listExportFiles', $this->obj);

        return $table;
    }
}